### ISSUE TITLE
Support unix sockets

### ISSUE THREAD

**Issue by salsa-dev** [adlandh/bitrix-memcached#1]
Hi!
Thanks very much for this library! It is working fine.
Any chance to support usage of unix sockets?

**Comment by adlandh** [comment]
Hi!
Unix sockets for what? To connect to memcached?

**Comment by salsa-dev** [comment]
Yes.
Sorry, I used the old notation of "unix:///tmp/memcached.sock" instead of just "/tmp/memcached.sock"

Now it working fine:

`               array("/tmp/memcached.sock", "0")`

May be you can put this into README or straight into settings example....

**Comment by salsa-dev** [comment]
I suggest to include an example into setting file.
#2

**Comment by adlandh** [comment]
Thank you, but I think it's better to use separated item in .settings.php, something similar to 'socket'=>array('/tmp/memcached.sock'). I'll add it in a few days. Thanks again for the suggestion)

**Comment by adlandh** [comment]
Added
